# 問題 ID (必須, 出力 html 名にも使用される)
id = "H"

# 制約の出力先となるファイル名
params_path = "./tests/constraints.hpp"

# 問題文が格納されている場所 (必須)
# Google Docs で問題文を管理している場合、Google Docs の URL または Document ID を記載する
# (Document ID とは Docs の URL にある、ランダムのような文字列のことです)
# 'path' は、以下に示す 2 種類の書き方が許容される
[[statements]]
path = "1MoguVNpp2SgJvF0ncPbp_8_x2_GhClMijUjF3U3g8ns"
# path = "https://docs.google.com/document/d/1MoguVNpp2SgJvF0ncPbp_8_x2_GhClMijUjF3U3g8ns/edit?usp=sharing"
lang = "en"

[constraints]
    MIN_N = 1
    MAX_N = 1000
    MIN_C = 1
    MAX_C = 100_000
    MIN_Q = 1
    MAX_Q = 100_000
    MIN_D = 1
    MAX_D = 100_000
